
name: snake-game

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest  # Assuming you use pytest for testing

      - name: Deploy (Optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying Snake Game..."
          # Add deployment script here (e.g., Docker, Firebase, etc.)
